### ISSUE TITLE
User's feed list sorting & followers count

### ISSUE THREAD

**Issue by sabre23t** [scripting/feedBase#27]
Ref your change http://scripting.com/2018/04/02.html#a220750 to sort user's feed list alphabetically by title, and don't include the follower count. I don't mind the alphabetical sorting, but I would appreciate seeing the follower count for my feed. 

My feed with 1 follower count (or small number) may merit me checking it out, it may indicate a non working feed. Or conversely it may mean a feed that I might want to publicise in my blog or other net presence. TQ.

**Comment by scripting** [comment]
I think you are right. I changed the way it works.

Now it sorts alphabetically on user-feed-lists, but includes the counts. 

Note that the counts are not the combined counts, so you'll only see the counts for the specific feed URL you're subscribed to, not the combination of all the aliases.

**Comment by drewkime** [comment]
People mostly leave comments when they don't like something. Just wanted to say this is surprisingly good. It made sense when I read the announcement, but seeing which of my feeds are popular with others is very interesting.

**Comment by scripting** [comment]
It is interesting to see the follower counts on feeds you follow. And thanks for the awareness. But I'm getting a good vibe from the users of this product. The feature requests I'm getting are sensible and often correct. That's really all I need.
