### ISSUE TITLE
Duplicate feeds/sits in hotlist OPML

### ISSUE THREAD

**Issue by frankmeeuwsen** [scripting/feedBase#32]
Currently, the OPML feed of the Hotlist shows multiple entries of the same site. Since the feed might differ, they look like separate entries. For instance, Daring Fireball is mentioned three times with different feeds. But all with the same htmlUrl. 
I would expect the list to have some sort deduplication like the webversion has.

**Comment by scripting** [comment]
Reload the page. There is de-duplication, you're running a cached version.

**Comment by frankmeeuwsen** [comment]
Are you sure? When I check http://opml.feedbase.io/hotlist.opml in both a normal and incognito browser I see duplicate entries. Even after several reloads.

**Comment by scripting** [comment]
You're right -- when I read the subject I missed the OPML at the end. The de-duplication is only on the home page, in HTML, not in the OPML.

**Comment by scripting** [comment]
Now it should be right. We're de-duplicating both the HTML and OPML versions now. Thanks for staying with it.  :boom:
