### ISSUE TITLE
Unable to upload OPML after changing Twitter handle

### ISSUE THREAD

**Issue by vincode-io** [scripting/feedBase#40]
I uploaded my OPML file under a previous twitter handle (mauricevineyard).  I then changed my twitter handle (my old handle didn't age well) and now I'm unable to upload or view OPML files under my current handle (vincode_io).

**Comment by scripting** [comment]
How to ask for help with software.

http://scripting.com/2014/03/19/howToAskForHelpWithSoftware.html

Dave

**Comment by vincode-io** [comment]
I'm sorry.  I don't understand.  I read the documents and I don't see any guidance on changing twitter handles.  Was the bug report not sufficient to understand or recreate the bug?

**Comment by scripting** [comment]
You're not making it easy for me. I would like to help you. But I need to know what you did, step by step, to upload your OPML and what error messages you received if any. How can you tell that the OPML files were not uploaded? Did you look in the JS console for error messages? You're making me work pretty hard to help you. ;-)

**Comment by scripting** [comment]
I just did what you described and it seems to have worked.

I had a Twitter account that I had never used with Feedbase.

I logged off, and then logged on using that account.

I uploaded an OPML file, the subscription list for podcatch.com.

I was taken to the page for the account, and all the subs appear to be
there.

One problem I noted was that View My OPML command in the Main menu was not
enabled. I'm going to look into that.

That's the kind of report I need. Step by step what you did, and what you
expected to happen. Because the problem may not be in the software, rather
your understanding of it.

**Comment by vincode-io** [comment]
Thanks for the quick responses.  I was concerned that project might not being maintained anymore.  

Step 1:  Sign in to feedBase with Twitter handle @mauricevineyard
Step 2:  Upload OPML file
Step 3:  Successfully verified OPML uploaded on "view my subs" page.
Step 4.  Log out of Twitter handle @mauricevineyard
Step 5.  Change Twitter handle on Twitter settings to @vincode_io
Step 6.  Sign in to feedBase with Twitter handle @vincode_io
Step 7.  Navigate to "View my subs" page.  No subscriptions displayed.
Step 8.  Upload OPML file.  No errors received on screen or in javascript console.
Step 9. Navigate to "View my subs" page.  No subscriptions displayed.

[Screen Recording 2019-03-16 at 10.51.40 AM.mov.zip](https://github.com/scripting/feedBase/files/2974063/Screen.Recording.2019-03-16.at.10.51.40.AM.mov.zip)

**Comment by scripting** [comment]
What does this mean?

"Change Twitter handle on Twitter settings to @vincode_io"

It doesn't appear as if you were ever logged on as vincode_io.

There's no record of it on the server.

I think you have to, on Twitter, log off your previous account and log on
as vincode_io, and then log on in Feedbase.

I don't think changing it in Twitter's dialog actually results in you
logging on as that user.

Dave

**Comment by vincode-io** [comment]
I didn't change accounts.  I changed the handle (username) on one twitter account.  I then logged out of twitter and then logged back in using vincode_io.

Here's how I changed my handle (username) in twitter:
![Screen Shot 2019-03-16 at 11 11 02 AM](https://user-images.githubusercontent.com/16448027/54478069-70103b80-47dc-11e9-9f70-5d720910aca9.png)

It is strange that the logs don't show vincode_io signing on.   Here's where feedBase is at least displaying the new handle (username):
![Screen Shot 2019-03-16 at 11 12 08 AM](https://user-images.githubusercontent.com/16448027/54478078-84543880-47dc-11e9-9aec-dbd353d8d60d.png)

**Comment by scripting** [comment]
Oy, I have no idea what the Twitter API does in this case. It may take a
while for me to get to looking at this.

**Comment by vincode-io** [comment]
Sounds great.  I'm really happy that this project is under active development.  Thanks again.

**Comment by vincode-io** [comment]
Are you interested in taking patches for this project?  I might be interested in becoming a contributor.

**Comment by scripting** [comment]
I treat patches as feature requests. This isn't a coding problem, it's a
question of what the Twitter API does in this situation. If you want to
research that, great. But the coding is the least of it.

**Comment by vincode-io** [comment]
I got an instance of feedBase up and running and this is what it looks like happened to me.

1. I logged in using mauricevineyard
2. The davetwitter module cached the screenname mauricevineyard in the screenNameCache
3. I logged off of mauricevineyard
4. I changed my screenname to vincode_io on twitter.com
5. I logged in using vincode_io
6. Twitter supplied the same accessToken and accessTokenSecret for vincode_io as it had for mauricevineyard
7. The davetwitter module found the previous screenname (mauricevineyard) because it accesses the screenNameCache using the accessToken and accessTokenSecret credentials

Because the getScreenName function was returning the old screenname, my uploads were getting uploaded to the old screenname.

I verified this in testing and was able to clear it up by restarting the server and clearing out the screenNameCache.

I hope this helps.

**Comment by scripting** [comment]
@vincode-io -- Thanks for this excellent report. I now understand what the problem is, and also know how to fix it. I'm back at work, after taking a few days off. Hope to have something to report soon. Thanks again.

**Comment by scripting** [comment]
@vincode-io -- I've made the change to [davetwitter](https://github.com/scripting/twitter), check the [readme file](https://github.com/scripting/twitter#v0510----32419-by-dw) for details.

Please report any problems, or success. 

Thanks again for the excellent work and report. ;-)

**Comment by vincode-io** [comment]
It worked!  Many thanks @scripting !

**Comment by scripting** [comment]
I :heart: fixing bugs.
